/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as EditorialSlugRouteImport } from './routes/editorial.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const EditorialSlugRoute = EditorialSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EditorialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/editorial/$slug'
    | '/portfolio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/editorial/$slug'
    | '/portfolio/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/editorial/$slug'
    | '/portfolio/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EditorialRoute: typeof EditorialRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/editorial/$slug': {
      id: '/editorial/$slug'
      path: '/$slug'
      fullPath: '/editorial/$slug'
      preLoaderRoute: typeof EditorialSlugRouteImport
      parentRoute: typeof EditorialRoute
    }
  }
}

interface EditorialRouteChildren {
  EditorialSlugRoute: typeof EditorialSlugRoute
}

const EditorialRouteChildren: EditorialRouteChildren = {
  EditorialSlugRoute: EditorialSlugRoute,
}

const EditorialRouteWithChildren = EditorialRoute._addFileChildren(
  EditorialRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EditorialRoute: EditorialRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
